# Generated by Django 5.1.6 on 2025-11-05 04:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adviser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image_url', models.URLField()),
                ('designation', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='events/')),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField(blank=True, null=True)),
                ('stadium', models.CharField(blank=True, default='', max_length=255)),
                ('team1_score', models.IntegerField(blank=True, null=True)),
                ('team1_overs', models.FloatField(default=0.0)),
                ('team2_score', models.IntegerField(blank=True, null=True)),
                ('team2_overs', models.FloatField(default=0.0)),
                ('result', models.CharField(blank=True, default='', max_length=255)),
                ('win_by_runs', models.IntegerField(blank=True, default=None, null=True)),
                ('win_by_wickets', models.IntegerField(blank=True, default=None, null=True)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('finished', 'Finished')], default='upcoming', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('pdf_link', models.URLField()),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bkash_number', models.CharField(blank=True, max_length=20, null=True)),
                ('bkash_transaction_id', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('district', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('nid_or_birth_certificate_no', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('area', models.CharField(choices=[('Local', 'Local'), ('Semi-Local', 'Semi-Local'), ('Overseas', 'Overseas')], max_length=20)),
                ('speciality', models.CharField(choices=[('Batsman', 'Batsman'), ('Bowler', 'Bowler'), ('All-Rounder', 'All-Rounder')], max_length=20)),
                ('player_category', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=1)),
                ('player_photo', models.ImageField(blank=True, null=True, upload_to='player_photos/')),
                ('is_registration_open', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('media', 'Media Sponsor'), ('co', 'Co-sponsor'), ('main', 'Main Sponsor')], max_length=50)),
                ('position', models.PositiveIntegerField(db_index=True, default=0)),
            ],
            options={
                'ordering': ['category', 'position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.CharField(blank=True, max_length=255, null=True)),
                ('color', models.CharField(default='#000000', max_length=7)),
                ('matches_played', models.IntegerField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('ties', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
                ('total_runs_scored', models.IntegerField(default=0)),
                ('total_overs_faced', models.FloatField(default=0.0)),
                ('total_runs_conceded', models.IntegerField(default=0)),
                ('total_overs_bowled', models.FloatField(default=0.0)),
                ('net_run_rate', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='YouTubeVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('video_link', models.URLField()),
                ('thumbnail_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MatchPhotoGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='match_photos/')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_photos', to='api.match')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SponsorImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banners/')),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.sponsor')),
            ],
        ),
        migrations.AddField(
            model_name='sponsor',
            name='image',
            field=models.ManyToManyField(blank=True, related_name='sponsor_related_image', to='api.sponsorimage'),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('role', models.CharField(choices=[('Batsman', 'Batsman'), ('Bowler', 'Bowler'), ('All-Rounder', 'All-Rounder'), ('Wicket-Keeper', 'Wicket-Keeper')], default='Batsman', max_length=20)),
                ('image_url', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(choices=[('Local', 'Local'), ('Semi-Local', 'Semi-Local'), ('Overseas', 'Overseas')], default='Local', max_length=20)),
                ('runs', models.IntegerField(default=0)),
                ('matches', models.IntegerField(default=0)),
                ('innings', models.IntegerField(default=0)),
                ('not_outs', models.IntegerField(default=0)),
                ('highest_score', models.CharField(default='0', max_length=10)),
                ('average', models.FloatField(default=0.0)),
                ('balls_faced', models.IntegerField(default=0)),
                ('strike_rate', models.FloatField(default=0.0)),
                ('hundreds', models.IntegerField(default=0)),
                ('fifties', models.IntegerField(default=0)),
                ('fours', models.IntegerField(default=0)),
                ('sixes', models.IntegerField(default=0)),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='api.team')),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('image_url', models.CharField(blank=True, max_length=255, null=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='api.team')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='team1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team1_matches', to='api.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='team2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team2_matches', to='api.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_matches', to='api.team'),
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image_url', models.CharField(blank=True, max_length=255, null=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coaches', to='api.team')),
            ],
        ),
    ]
