# Generated by Django 5.1.6 on 2025-03-23 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_match_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('finished', 'Finished')], default='upcoming', max_length=20),
        ),
        migrations.AlterField(
            model_name='match',
            name='team1_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='team2_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
