# Generated by Django 5.1.6 on 2025-03-24 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_match_stadium_match_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('pdf_link', models.URLField()),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
