# Generated by Django 5.1.6 on 2025-03-24 09:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdf',
            name='upload_date',
        ),
        migrations.AddField(
            model_name='pdf',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pdf',
            name='description',
            field=models.TextField(default=datetime.time(0, 0)),
            preserve_default=False,
        ),
    ]
