# Generated by Django 5.1.6 on 2025-04-08 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_team_net_run_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='net_run_rate',
            field=models.FloatField(default=0.0),
        ),
    ]
