# Generated by Django 5.1.6 on 2025-06-18 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_team_net_run_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bkash_number', models.CharField(blank=True, max_length=20, null=True)),
                ('bkash_transaction_id', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('district', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('nid_or_birth_certificate_no', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('area', models.CharField(choices=[('Local', 'Local'), ('Semi-Local', 'Semi-Local'), ('Overseas', 'Overseas')], max_length=20)),
                ('speciality', models.CharField(choices=[('Batsman', 'Batsman'), ('Bowler', 'Bowler'), ('All-Rounder', 'All-Rounder')], max_length=20)),
                ('player_category', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=1)),
                ('player_photo', models.ImageField(blank=True, null=True, upload_to='player_photos/')),
            ],
        ),
    ]
