# Generated by Django 5.1.6 on 2025-07-14 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_playerregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='banners/')),
            ],
        ),
        migrations.AddField(
            model_name='playerregistration',
            name='is_registration_open',
            field=models.BooleanField(default=True),
        ),
    ]
