# Generated by Django 5.1.6 on 2025-07-14 20:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_sponsor_playerregistration_is_registration_open'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchPhotoGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='match_photos/')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_photos', to='api.match')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
