# Generated by Django 5.1.6 on 2025-07-16 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_owner_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='category',
            field=models.CharField(choices=[('media', 'Media Sponsor'), ('co', 'Co-sponsor'), ('main', 'Main Sponsor')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
