# Generated by Django 5.1.6 on 2025-11-02 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_event_alter_sponsor_options_sponsor_position_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsor',
            name='image',
        ),
        migrations.AddField(
            model_name='adviser',
            name='category',
            field=models.CharField(choices=[('chief', 'Chief Adviser'), ('senior', 'Senior Adviser'), ('general', 'General Adviser')], default='general', max_length=50),
        ),
        migrations.CreateModel(
            name='SponsorImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banners/')),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.sponsor')),
            ],
        ),
    ]
