# Generated by Django 5.1.6 on 2025-11-03 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_remove_sponsor_image_adviser_category_sponsorimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adviser',
            name='category',
        ),
        migrations.AddField(
            model_name='sponsor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sponsor',
            name='image',
            field=models.ImageField(default=1, upload_to='banners/'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='SponsorImage',
        ),
    ]
